services:
  - type: web
    name: background-remover
    runtime: python
    buildCommand: "pip install uv && uv sync"
    startCommand: "uvicorn api:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0