name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          # Create app directory
          mkdir -p ~/apps/background-remover
          cd ~/apps/background-remover
          
          # Clone or pull latest code
          if [ ! -d ".git" ]; then
            git clone https://github.com/${{ github.repository }}.git .
          else
            git pull origin main
          fi
          
          # Check if Python 3.12 is installed
          if ! command -v python3.12 &> /dev/null; then
            echo "Python 3.12 not found. Installing..."
            sudo apt update
            sudo apt install -y software-properties-common
            sudo add-apt-repository -y ppa:deadsnakes/ppa
            sudo apt update
            sudo apt install -y python3.12 python3.12-venv python3.12-dev
          fi
          
          # Install uv if not present
          if ! command -v uv &> /dev/null; then
            echo "Installing uv..."
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> ~/.bashrc
            export PATH="$HOME/.cargo/bin:$PATH"
          fi
          
          # Create virtual environment and install dependencies
          python3.12 -m venv .venv
          source .venv/bin/activate
          pip install uv
          uv sync
          
          # Stop existing service
          sudo systemctl stop background-remover || true
          
          # Copy and enable systemd service
          sudo cp deploy/background-remover.service /etc/systemd/system/
          sudo systemctl daemon-reload
          sudo systemctl enable background-remover
          sudo systemctl start background-remover
          
          # Check service status
          sudo systemctl status background-remover --no-pager
          
          # Setup nginx if needed
          if ! command -v nginx &> /dev/null; then
            echo "Installing nginx..."
            sudo apt install -y nginx
          fi
          
          # Copy nginx configuration
          sudo cp deploy/nginx-background-remover.conf /etc/nginx/sites-available/background-remover
          sudo ln -sf /etc/nginx/sites-available/background-remover /etc/nginx/sites-enabled/
          sudo nginx -t && sudo systemctl reload nginx
          
          echo "Deployment completed!"